import type { Request, Response } from "express"
import { buildOpenApiSpec } from "../../lib/openapiSpec"

/**
 * Live OpenAPI 3.1 spec generated by introspecting the running Express
 * route stack at request time. No cache — the spec is cheap to build
 * and we want it to reflect hot-reloaded routes during dev.
 */
export function getOpenApi(req: Request, res: Response): void {
  // Reaching into req.app.locals.expressApp gives us the root Application
  // when admin.routes is mounted as a sub-router. Fall back to req.app
  // (which IS the Application in production).
  const app = (req.app as { locals?: { rootApp?: typeof req.app } }).locals?.rootApp ?? req.app
  const spec = buildOpenApiSpec(app)
  res.status(200).json(spec)
}
